### ISSUE TITLE
下载到一个视频时崩溃，panic: truncate xxxxx.flv: no such file or directory

### ISSUE THREAD

**Issue by Freddd13** [Privilege-privacy/BiliBackup#2]
感谢作者的项目，十分需要。
我在运行备份一个收藏夹时，下载到第三个视频时报错如下：

```bash
root@xxx:/mnt/block50gb# ~/BiliBackup -f 978536184 -pn 100000 -remote onedrive:/bilibili_backup
2023/04/29 10:16:35 开始下载：  【2023年4月/种崎敦美】魔法使的新娘 第二季 先导PV【MCE汉化组】.flv
panic: truncate /mnt/block50gb/download/【2023年4月/种崎敦美】魔法使的新娘 第二季 先导PV【MCE汉化组】.flv: no such file or directory

goroutine 1 [running]:
github.com/monkeyWie/gopeed-core/pkg.Download({0xc00076a98b, 0x254}, {0xc0005b0420, 0x59}, 0xc000101800)
        /home/ubuntu/go/pkg/mod/github.com/!privilege-privacy/gopeed@v0.0.4/pkg/download.go:54 +0x1b3
BiliBackup/core/bili.Run({0xc0000276ff, 0xc}, {0x7ffe023a77b9, 0x19})
        /home/ubuntu/BiliBackup/core/bili/cid.go:67 +0x265
BiliBackup/core/bili.GetfavBvid.func1({0x2, {0x0, 0x0}, {0x0, 0x0}, 0x4008000000000000, 0x0, {0x0, 0x0, 0x0}}, ...)
        /home/ubuntu/BiliBackup/core/bili/bili.go:22 +0x33c
github.com/tidwall/gjson.Result.ForEach({0x5, {0xc000026a51, 0x40b9}, {0x0, 0x0}, 0x0, 0x251, {0x0, 0x0, 0x0}}, ...)
        /home/ubuntu/go/pkg/mod/github.com/tidwall/gjson@v1.14.4/gjson.go:297 +0x529
BiliBackup/core/bili.GetfavBvid(0xc000072420?)
        /home/ubuntu/BiliBackup/core/bili/bili.go:18 +0x1d4
main.main()
        /home/ubuntu/BiliBackup/main.go:42 +0xec
```

请问是什么原因导致的？
测试收藏夹id: `978536184`

**Comment by Privilege-privacy** [comment]
现在应该可以了 ，可以试试这个版本 [Release](https://github.com/Privilege-privacy/BiliBackup/releases/tag/v0.1.3)

**Comment by Freddd13** [comment]
后面又有一些视频会失败
```bash
2023/04/30 15:21:13 开始下载：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv http://upos-hz-mirrorakam.akamaized.net/upgcxcode/13/68/50416813/50416813_da2-1-16.mp4?e=ig8euxZM2rNcNbRzhbUVhoM1hzNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1682875272&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=240e1f20430c44e69acd0edd0b4980d6&uipk=5&upsig=35d73d5ad5cc3edb94af798eed3381b9&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1682875272~hmac=5c71b48ea623bd08e4b2ee71d8733b9a2a0f6b1fc380e2c24f27c441b5304d69&mid=0

2023/04/30 15:21:13 下载失败：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv

-----------------------
2023/04/30 15:21:44 下载失败：  【中字最终回】想和佐仓做的大西 第365回（2023.03.28）【本篇+安可+反省会】.flv
```
我把这两个视频放在一个新的收藏夹 `2309557084`

**Comment by Privilege-privacy** [comment]
> 后面又有一些视频会失败
> 
> ```shell
> 2023/04/30 15:21:13 开始下载：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv http://upos-hz-mirrorakam.akamaized.net/upgcxcode/13/68/50416813/50416813_da2-1-16.mp4?e=ig8euxZM2rNcNbRzhbUVhoM1hzNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1682875272&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=240e1f20430c44e69acd0edd0b4980d6&uipk=5&upsig=35d73d5ad5cc3edb94af798eed3381b9&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1682875272~hmac=5c71b48ea623bd08e4b2ee71d8733b9a2a0f6b1fc380e2c24f27c441b5304d69&mid=0
> 
> 2023/04/30 15:21:13 下载失败：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv
> 
> -----------------------
> 2023/04/30 15:21:44 下载失败：  【中字最终回】想和佐仓做的大西 第365回（2023.03.28）【本篇+安可+反省会】.flv
> ```
> 
> 我把这两个视频放在一个新的收藏夹 `2309557084`

我测试了位于收藏夹号为 `2309557084 ` 的视频，发现可以正常下载，所以我只能在视频下载失败时，加上三次错误重试。
不过，当下载视频失败时。如果再次运行命令，由于已经存在 bili.db 文件，程序只会下载之前未能成功下载的视频。

[v0.1.3](https://github.com/Privilege-privacy/BiliBackup/releases/tag/v0.1.3) 这个版本我已删除重新构建了。

**Comment by Freddd13** [comment]
我试了下还是下不了，错误是:
```bash
 ~/BiliBackup_Linux_x86_64  -f 2309557084 -pn 100000 -remote onedrive:/bilibili_backup/test
2023/05/01 13:14:29 开始下载：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv
2023/05/01 13:14:30 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：Range request returned invalid Content-Length: 273 however the range was: bytes=99845460-199690919)
2023/05/01 13:14:30 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：Range request returned invalid Content-Length: 273 however the range was: bytes=99845460-199690919)
2023/05/01 13:14:31 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：unexpected EOF)
2023/05/01 13:14:31 下载 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv 失败，重试次数超过最大限制 3 次
```

**Comment by Privilege-privacy** [comment]
> 

之前默认是多线程下载，现在如果某个视频多线程下载失败后，会

> 我试了下还是下不了，错误是:
> 
> ```shell
>  ~/BiliBackup_Linux_x86_64  -f 2309557084 -pn 100000 -remote onedrive:/bilibili_backup/test
> 2023/05/01 13:14:29 开始下载：  【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv
> 2023/05/01 13:14:30 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：Range request returned invalid Content-Length: 273 however the range was: bytes=99845460-199690919)
> 2023/05/01 13:14:30 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：Range request returned invalid Content-Length: 273 however the range was: bytes=99845460-199690919)
> 2023/05/01 13:14:31 下载失败: 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv, 重试中... (错误：unexpected EOF)
> 2023/05/01 13:14:31 下载 【Event】魔法使的新娘 ｢スペシャルイベント～紡がれる、魔法の世界～｣.flv 失败，重试次数超过最大限制 3 次
> ```

看报错应该是多线程下载出了问题，现在当多线程下载不了时，这个视频就会以单线程下载。
[v0.1.3](https://github.com/Privilege-privacy/BiliBackup/releases/tag/v0.1.3)

**Comment by Freddd13** [comment]
```bash
root@root:/mnt/block50gb# ./BiliBackup_Linux_x86_64  -f 978536184 -pn 100000 -remote onedrive:/bilibili_backup
2023/05/02 13:50:12 failed to get download URL: BV1E4411s7hn
2023/05/02 13:50:16 Failed to start download: unexpected EOF
2023/05/02 13:50:16 download failed (1/3): 【魔法使的新娘】OST原声集.flv, retrying... (error: unexpected EOF)
2023/05/02 13:50:19 Failed to start download: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/40/23/28642340/28642340_da3-1-64.flv?e=ig8euxZM2rNcNbUghbUVhoMBhbNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042613&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=b7c4b87eda554dcc8fa0e9942fac34c2&uipk=5&upsig=5104c04822973e661f46292dadaba381&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042613~hmac=5f0674eebad8b66968a7cd3c2b8edf0e5e53ff04979635bc74132e8af92ace9c&mid=0": EOF
2023/05/02 13:50:19 download failed (2/3): 【魔法使的新娘】OST原声集.flv, retrying... (error: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/40/23/28642340/28642340_da3-1-64.flv?e=ig8euxZM2rNcNbUghbUVhoMBhbNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042613&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=b7c4b87eda554dcc8fa0e9942fac34c2&uipk=5&upsig=5104c04822973e661f46292dadaba381&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042613~hmac=5f0674eebad8b66968a7cd3c2b8edf0e5e53ff04979635bc74132e8af92ace9c&mid=0": EOF)
2023/05/02 13:50:20 Failed to start download: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/40/23/28642340/28642340_da3-1-64.flv?e=ig8euxZM2rNcNbUghbUVhoMBhbNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042613&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=b7c4b87eda554dcc8fa0e9942fac34c2&uipk=5&upsig=5104c04822973e661f46292dadaba381&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042613~hmac=5f0674eebad8b66968a7cd3c2b8edf0e5e53ff04979635bc74132e8af92ace9c&mid=0": EOF
2023/05/02 13:50:20 download failed (3/3): 【魔法使的新娘】OST原声集.flv, retrying... (error: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/40/23/28642340/28642340_da3-1-64.flv?e=ig8euxZM2rNcNbUghbUVhoMBhbNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042613&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=b7c4b87eda554dcc8fa0e9942fac34c2&uipk=5&upsig=5104c04822973e661f46292dadaba381&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042613~hmac=5f0674eebad8b66968a7cd3c2b8edf0e5e53ff04979635bc74132e8af92ace9c&mid=0": EOF)
2023/05/02 13:50:20 multi-threaded download of 【魔法使的新娘】OST原声集.flv failed after 3 retries, attempting single-threaded download...
2023/05/02 13:50:21 uploading: 【魔法使的新娘】OST原声集.flv

2023/05/02 13:50:32 /home/runner/work/BiliBackup/BiliBackup/core/bili/cid.go:195 SLOW SQL >= 200ms
[204.759ms] [rows:1] INSERT INTO `bilis` (`created_at`,`updated_at`,`deleted_at`,`bvid`) VALUES ("2023-05-02 13:50:32.256","2023-05-02 13:50:32.256",NULL,"BV1ZW41187Sn") RETURNING `id`
-------------
2023/05/02 13:50:32 failed to get download URL: BV1jb41177AR
2023/05/02 13:50:34 Failed to start download: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/52/26/107912652/107912652-1-80.flv?e=ig8euxZM2rNcNbeahwdVhoMH7zdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042633&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=ed6b2f1b20b143d2867380c67facf1ef&uipk=5&upsig=466f1508c462917d9370d8d647264c2c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042633~hmac=45022f8c41d5f5dba4b18b7dbc0352154bdc57f2e343ab13b40275a7a63f0284&mid=0": EOF
2023/05/02 13:50:34 download failed (1/3): 魔法使的新娘第一季 OPED Mahou Tsukai no Yome.flv, retrying... (error: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/52/26/107912652/107912652-1-80.flv?e=ig8euxZM2rNcNbeahwdVhoMH7zdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042633&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=ed6b2f1b20b143d2867380c67facf1ef&uipk=5&upsig=466f1508c462917d9370d8d647264c2c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042633~hmac=45022f8c41d5f5dba4b18b7dbc0352154bdc57f2e343ab13b40275a7a63f0284&mid=0": EOF)
2023/05/02 13:50:37 uploading: 魔法使的新娘第一季 OPED Mahou Tsukai no Yome.flv

2023/05/02 13:50:45 /home/runner/work/BiliBackup/BiliBackup/core/bili/cid.go:195 SLOW SQL >= 200ms
[259.314ms] [rows:1] INSERT INTO `bilis` (`created_at`,`updated_at`,`deleted_at`,`bvid`) VALUES ("2023-05-02 13:50:45.093","2023-05-02 13:50:45.093",NULL,"BV1St411u7di") RETURNING `id`
-------------
2023/05/02 13:50:46 Failed to start download: Range request returned invalid Content-Length: 271 however the range was: bytes=8885276-13327912
2023/05/02 13:50:46 download failed (1/3): 【Animenz】Here 魔法使いの嫁（魔法使的新娘） OP 钢琴改编.flv, retrying... (error: Range request returned invalid Content-Length: 271 however the range was: bytes=8885276-13327912)
2023/05/02 13:50:48 uploading: 【Animenz】Here 魔法使いの嫁（魔法使的新娘） OP 钢琴改编.flv

2023/05/02 13:50:53 /home/runner/work/BiliBackup/BiliBackup/core/bili/cid.go:195 SLOW SQL >= 200ms
[301.830ms] [rows:1] INSERT INTO `bilis` (`created_at`,`updated_at`,`deleted_at`,`bvid`) VALUES ("2023-05-02 13:50:53.541","2023-05-02 13:50:53.541",NULL,"BV1UE41187KS") RETURNING `id`
-------------
2023/05/02 13:50:55 uploading: 【钢琴】魔法使的新娘 OP  Here.flv

2023/05/02 13:50:59 /home/runner/work/BiliBackup/BiliBackup/core/bili/cid.go:195 SLOW SQL >= 200ms
[291.738ms] [rows:1] INSERT INTO `bilis` (`created_at`,`updated_at`,`deleted_at`,`bvid`) VALUES ("2023-05-02 13:50:59.043","2023-05-02 13:50:59.043",NULL,"BV1jx411u7Yz") RETURNING `id`
-------------
2023/05/02 13:51:00 Failed to start download: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/08/149490896/149490896-1-80.flv?e=ig8euxZM2rNcNbeBhbUVhoMH7WNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042659&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=0dd52f0a45fd43939777813b117a5f69&uipk=5&upsig=7ed5dd30d0341161f6d6a88c5bb2ea39&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042659~hmac=a9a94339ffaba33e02f1b1fba18c8fe8356d99b7780a39c2606fad80114b1a46&mid=0": EOF
2023/05/02 13:51:00 download failed (1/3): 【Mevia】Here - JUNNA | 魔法使的新娘OP | 钢琴翻弹 | A叔Animenz版.flv, retrying... (error: Get "http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/08/149490896/149490896-1-80.flv?e=ig8euxZM2rNcNbeBhbUVhoMH7WNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1683042659&gen=playurl&nbs=1&oi=1755895697&os=akam&platform=pc&trid=0dd52f0a45fd43939777813b117a5f69&uipk=5&upsig=7ed5dd30d0341161f6d6a88c5bb2ea39&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1683042659~hmac=a9a94339ffaba33e02f1b1fba18c8fe8356d99b7780a39c2606fad80114b1a46&mid=0": EOF)
2023/05/02 13:51:57 uploading: 【Mevia】Here - JUNNA | 魔法使的新娘OP | 钢琴翻弹 | A叔Animenz版.flv
^C
```

有的时候直接变成下面这样就退出了：
```bash
root@hwsrv-941614:/mnt/block50gb# ./BiliBackup_Linux_x86_64  -f 978536184 -pn 100000 -remote onedrive:/bilibili_backup
2023/05/02 13:55:35 failed to get download URL: BV1E4411s7hn
2023/05/02 13:55:36 failed to get download URL: BV1jb41177AR
```
这个链接我自己都是能打开的.. 另外这看起来似乎在报错了之后也插入数据库？不懂后端- - 痛苦面具啊

**Comment by Privilege-privacy** [comment]
> 

`2023/05/02 13:50:59 /home/runner/work/BiliBackup/BiliBackup/core/bili/cid.go:195 SLOW SQL >= 200ms`
这只是 ORM 的提醒，其实不用管。

> 另外这看起来似乎在报错了之后也插入数据库？

只有视频成功下载并上传后，才会被插入数据库，所以不用担心视频没有被正常下载，就被数据库记录的情况。
只要能看见类似于 `2023/05/02 13:50:55 uploading: 【钢琴】魔法使的新娘 OP  Here.flv` 就是能够正常处理的。

`multi-threaded download of 【魔法使的新娘】OST原声集.flv failed after 3 retries, attempting single-threaded download...`
单线程下载完成后，我没有打印下载完毕，确实不太好辨别，有种还没下载成功就被上传的感觉。

```
root@hwsrv-941614:/mnt/block50gb# ./BiliBackup_Linux_x86_64  -f 978536184 -pn 100000 -remote onedrive:/bilibili_backup
2023/05/02 13:55:35 failed to get download URL: BV1E4411s7hn
2023/05/02 13:55:36 failed to get download URL: BV1jb41177AR
```
这是下载接口 API 有问题。API 详细报错为 `{"code":-404,"message":"啥都木有","ttl":1}`， 我也没啥办法，并且触发原因不明，有时候正常返回下载地址，有时候就报错，很迷。
也许更换下载 API 能够解决，但是更换后，就得强依赖 ffmpeg 合并视频音频了。

**Comment by Freddd13** [comment]
辛苦了，感谢回复！
不知道还有没有其他的api，有没有可能对失败的视频轮换多个途径尝试…毕竟对备份来说下得全是第一要务😄
另外我这下载失败的视频似乎总是报content length的错误，这似乎是一个请求上的问题？
